project:
  type: website
  output-dir: docs/ 

lang: pt

website:
  page-navigation: true
  title: "Quarto - A nova geração do RMarkdown"
    
  sidebar:
    title: "Quarto - A nova geração do RMarkdown <br>"
    background: "#FFFFFF" 
    foreground: "#562457"
    logo: img/logo.jpg
    pinned: true
    align: center
    style: "docked"
    search: true
    collapse-level: 1    
    tools:
      - icon: github
        href: https://github.com/beatrizmilz/202211-quarto-amostra-IME-USP
        text: "GitHub Repository"
    
    contents:
      - href: index.qmd
        text: "Página inicial" 
      - href: speaker.qmd  
      - section: "Materiais"
        contents:
           - slides.qmd

  

        
        
  page-footer: 
    right: "Página criada com [Quarto](https://quarto.org/). "
    left: "&copy; Copyright 2022, Beatriz Milz"
    background: "#562457"
            

  


format:
  html:
    theme: cosmo
    css: custom.css
    toc: true
    code-copy: true
    code-link: true
    code-overflow: wrap

editor: visual

execute:
  freeze: true
